### ISSUE TITLE
Adding a clock agent

### ISSUE THREAD

**Issue by argenos** [HBRS-MAAS/project#33]
@HBRS-MAAS/right-brothers can you add a few lines describing your approach for the TimeKeeper agent with discrete timesteps see

**Comment by DharminB** [comment]
- TimeKeeper sends a timeStep message to each and every alive agent.
- After getting this message the agent is allowed to do any task that it has to do in that time step. Once the agent it finished with its task, it informs the TimeKeeper that it is finished with all the tasks for this time step. Now, the agent should not perform any task and just wait for TimeKeeper to send another timeStep message.
- TimeKeeper will wait for finished message from all alive agents and once it receives them, it will send another timeStep message to all alive agents so that they carry on with their tasks for the next time step.

The BaseAgent will take care of the communication between TimeKeeper agent. Thus, all agent extending BaseAgent will have to only worry about 2 things
- Calling `finished()` method when they are finished with the task for current time step
- Do not execute a `Behaviour` (generic behaviour) `action` unless `baseAgent.allowAction` is `true`

Please see more detail and example [here](https://github.com/HBRS-MAAS/project/issues/39)
