### ISSUE TITLE
Agent base class

### ISSUE THREAD

**Issue by argenos** [HBRS-MAAS/project#39]
This base class will be in charge of sending messages to the corresponding visualization agents and synchronizing with the clock agent. Further, it can provide a mechanism to maintain a priority queue which can be used in the logic by agents who receive information from the previous stage.

**Comment by DharminB** [comment]
The code for `BaseAgent` and `TimeKeeper` is now available. [pull request](https://github.com/HBRS-MAAS/project/pull/45)

# Usage
- Use `extends BaseAgent` instead of `extends Agent` when defining the agent class
- Use `super.setup()` inside `setup()` method of agent class. This helps `BaseAgent` to initiate communication with `TimeKeeper`
- Use `this.register(agent_type, "JADE-bakery")` in `setup()` method of agent class. This registers agents with yellow pages. `agent_type` can be 
  - `Customer`
  - `Order-Processor`
  - `Oven`
  - etc
- Use `this.deRegister()` in `doDelete()` method of agent class. This removes the agent from yellow pages.


# Send Message
Use `baseAgent.sendMessage(message)` instead of `myAgent.send(message)` for sending messages to another agent. This helps `BaseAgent` to use the messages for visualisation agents.

# Time Keeping changes
### Calling `baseAgent.finished()`
Call `baseAgent.finished()` when the agent is finished with the task for current time step. For examples see Examples section below
### Blocking actions
Block  `Behaviour` (generic behaviour) class by using following codes at the beginning of `action()` method
```
if (!baseAgent.allowAction) {
    return;
}
```
This ensures that the agent does not perform actions of future time step. See [this](https://github.com/HBRS-MAAS/project/issues/33) for more info. **Note**: Do not block `action()` method of `CyclicBehaviour`. 

# Queue
To be implemented.

# Examples
Following is the code snippet of a generic behaviour for sending a INFORM message to another agent and waiting for its CONFIRM reply. This is very similar to customer agent's behaviour from 2nd assignment. The aim of this example is to show how to take advantage of `BaseAgent` and `TimeKeeper` agents.
```
    private class RequestPerformer extends Behaviour {
        private MessageTemplate mt;
        private int step = 0;
        
        public void action() {
            // blocking action
            if (!baseAgent.allowAction) {
                return;
            }
            switch (step) {
            case 0:
                ACLMessage inf = new ACLMessage(ACLMessage.INFORM);
                inf.addReceiver(sellerAgent);
                inf.setContent("Hello");
                inf.setConversationId("trade-example");
                inf.setReplyWith("inf"+System.currentTimeMillis());
                baseAgent.sendMessage(cfp);  // calling sendMessage instead of send
                mt = MessageTemplate.and(MessageTemplate.MatchConversationId("trade-example"),
                MessageTemplate.MatchInReplyTo(cfp.getReplyWith()));
                step = 1;
                break;
            case 1:
                ACLMessage reply = myAgent.receive(mt);
                if (reply != null) {
                    if (reply.getPerformative() == ACLMessage.CONFIRM) {
                        System.out.println("Received confirmation");
                        step = 2;
                    }
                }
                else {
                    block();
                }
                break;
            default:
                break;
            }
        }
        public boolean done() {
            if (step == 2) {
                baseAgent.finished(); // calling finished method
                myAgent.doDelete();
                return true;
            }
            return false;
        }
    }
```
Below is the behaviour that talks with the code shown above. This is similar to `OrderProcessingAgent` of 2nd assignment.
```
    private class OfferRequestsServer extends CyclicBehaviour {
        public void action() {
            baseAgent.finished(); //calling finished because there are no generic behaviours
            MessageTemplate mt = MessageTemplate.MatchPerformative(ACLMessage.INFORM);
            ACLMessage msg = myAgent.receive(mt);
            if (msg != null) {
                String content = msg.getContent();
                ACLMessage reply = msg.createReply();
                reply.setPerformative(ACLMessage.CONFIRM);
                reply.setContent("Received greetings");
                baseAgent.sendMessage(reply);
            }
            else {
                block();
            }
        }
    }
```
### Some suggestions and recommendations
The suggestions provided below are not hard rules. They are here because we think they will make the integration of `BaseAgent` and `TimeKeeper` with any agent easier.
- If there is only `CyclicBehaviour`s in a agent class (meaning there are no generic behaviours), call `baseAgent.finished()` as the first line of one of these behaviours. Do not block any `CyclicBehaviour` based on `baseAgent.allowAction`.
- For `Behaviour` (generic behaviour), add `baseAgent.finished()` inside `done()` method. This helps divide very long switch statements with long conversations into multiple time steps. Do not follow this suggestion, if you would like to have the whole conversation to happen in single time step.
- Create issues for bugs and suggestions and questions for the code [here](https://github.com/HBRS-MAAS/ws18-project-right-brothers/issues).

@HBRS-MAAS/ws18

**Comment by Sushant-Chavan** [comment]
@HBRS-MAAS/right-brothers We would like to request a slight refactoring of the BaseAgent class. 

We  have a few agents which do not depend on the time such as a StreetNetworkAgent which only responds to queries related to time to travel or path between two nodes. We would like to have a baseAgent that helps us register with Yellow pages, but does not involve dealing with the clock agent. For this we suggest the below change:
Instead of on single base class, we could separate the functionality of 'acting based on time'. With this we could have a class called BaseAgent which only provides a means to register and de register from the yellow pages as well as sending messages to visualization agents. Another agent called TimedAgent could be created which extends the BaseAgent and provides the functionality of acting only at specific time intervals.

Let us know i this can be supported,

Thanks!
@HBRS-MAAS/commitment_issues

**Comment by argenos** [comment]
I think in this case @HBRS-MAAS/commitment_issues you can create a pull request, which @HBRS-MAAS/right-brothers can then review.

**Comment by DharminB** [comment]
> We have a few agents which do not depend on the time such as a StreetNetworkAgent which only responds to queries related to time to travel or path between two nodes. 

If the requirements are as described above, we would highly recommend to not make StreetNetwork an agent as it clearly only mimics a lookup table functionality. Unless an entity makes changes to the world and/or acts independently, they should not be considered agents (please refer slide `Introduction.pdf` page 30 and `Intelligent Agents.pdf` page 10)
> We would like to have a baseAgent that helps us register with Yellow pages, but does not involve dealing with the clock agent. For this we suggest the below change:
> Instead of on single base class, we could separate the functionality of 'acting based on time'. With this we could have a class called BaseAgent which only provides a means to register and de register from the yellow pages as well as sending messages to visualization agents. Another agent called TimedAgent could be created which extends the BaseAgent and provides the functionality of acting only at specific time intervals.

According to [this](https://user-images.githubusercontent.com/17234248/48140791-ce1a9880-e2a9-11e8-8605-e49b2bb1abc7.png) design and discussion in class, the only "agents" which can be allowed to ignore time keeping stuff is the clock agent and visualisation agents. This is obvious because every other agent is working **with** other agents in a simulated world, where time is (and should be) constant for everyone. Clock agent is allowed to escape from this because it controls time (with the help of all agents) and visulisation agents are allowed to escape this because they act as monitors to the whole simulation (in other words has no direct influence on the simulation).

For the above mentioned reasons, we @HBRS-MAAS/right-brothers team highly discourage this implementation request and additionally request you to not invest your precious time on implementing it any further.
Thank you for the question.

**Comment by Sushant-Chavan** [comment]
The StreetNetwork was just an example. We believe that there are many agents that do not actually need to depend on the time. Another example is the TransportAgent whose job is to auction delivery orders to the trucks. This agent asynchronously receives order fulfillment messages and has no reason to wait until the next time step to begin the auction. The auctioning can be done immediately and the Trucks (which actually depend on the time) can then wait before starting to move. 

It does not make sense to make any pure auctioneer agent depend on time. Even if it has to, it is not clear when to call _finished_ for such agents. I see that one possible strategy is to create a cyclic behavior that keeps calling finished unconditionally, but this has two major drawbacks. First, the Timer agent depends on the count of live agents and there is no check to detect if the agent has already called _finished()_ earlier in the current time frame. This can cause a single agent to trigger the time increment even before other agents get to complete their tasks and call finish. Secondly, having a cyclic behavior that keeps calling finish will just keep the CPU utilization to maximum, since this thread is in an infinite loop. Having just a few of such agents can potentially slow down the entire system.

Regarding the StreetNetwork agent, it is created as an agent since it has the capability to provide services related to time between nodes or node position to any agent that may be interested in it. For now it is restricted to delivery stage, but could be later used by other agents such as order scheduler to get an estimate of the time needed to move from a bakery to a customer. The StreetNetwork is not just a representation of the network but actually does quite a bit including, but not limited to running a djkstra's algorithm, estimating time between two points, estimating the time along a set of waypoints, communicating with the Visualization agent for providing the node positions etc. We firmly believe that such behaviors warrant the creation of the StreetNetwork as an agent instead of an object.

Regarding the design decision, we like the idea that each agent informs the clock when it is done executing its current task. However, this could lead to a low maintainability of the code as the number of agents in the system grows. For example, if even one of the agent skips calling the _finished()_ method (for whatever reason), the entire system (all the stages) can come to a standstill and it could be a nightmare debugging such a scenario. This is another major reason why we suggest that timed agents are kept as low as possible and not force all agents to extend the timing functionality. 


Thanks for the feedback. @HBRS-MAAS/right-brothers

**Comment by Sushant-Chavan** [comment]
> This is not true in the way we recommend to make CyclicBehaviours. Generally CyclicBehaviour are supposed to be small, quickly executable and blocked unless used (by programmers) (refer JADE Programming Tutorial for Beginners.pdf page 10). This means that typically server type CyclicBehaviours (which describes the use cases described in question) will be blocked until a new message arrives in agent's queue. Thus, this behaviour will not resemble an infinite loop if used correctly.

I am aware of this. I guess you didn't get what I wanted to say earlier. The very requirement that the behavior is blocked until a new message arrives can cause deadlock issues. For example, our TransportAgent that is in the delivery stage will never receive a message until there are some boxes that need to be delivered. Lets assume all the previous stages take 10 hrs to complete, so the first message that will be posted to the transport agent will be after 10 hrs. Now if the cyclic behavior to call _finished()_ is blocked (as per your suggestion), we will never be able to call finish (as we ware waiting for a new message to wake up the behavior) and therefore the timer will never update time. We will be stuck in kind of a deadlock situation. 

> If the above mentioned StreetNetwork only did the tasks mentioned, then it would still not satisfy the criteria for making it an agent. The reason would be same as mentioned previously. For example, Djkstra's algo and estimating distance and time are not (in any way) related to agent communication or make any changes to the sim world. For communication with visualization agent, the node position can be simply obtained with a use of simple getter method from vis agent to query StreetNetwork. We believe that the above mentioned tasks are not "behaviours" but are simply methods of database wrapper. For the features that StreetNetwork does/will provide that are not mentioned above, we cannot comment.

Like I said, the StreetNetwork is just an example (one among the potentially many), Even if we assume that we make StreetNetwork an Object, how do you say we handle other agents such as the TransportAgent which is an auctioneer or the MailboxAgent (acting as a relay) which just receives messages from a single truck and forwards copies of it to interested agents?. Also since the topic of discussion is how to improve the BaseAgent to satisfy different types of agents and not about the design of StreetNetwork in particular, I would like to talk on a general scale from here onwards.

> The design of TimeKeeper is solely based on the trust that all agents will call finished(). Building on this fact, if an agent does not call finished() then the system assumes that the agent is performing some task that it needs to perform in that particular time step. We completely agree on that fact that the agents which depend on time should be as low as possible, and that is one of the non dominant reason why we recommend to keep StreetNetwork as an Object.

With this design choice I agree we need to rely on trust that everyone uses the BaseAgent in the perfect way. But in reality I expect a lot of people to make mistakes (atleast when using it for the first few times). Everyone is going to take a lot of time debugging such situations, and in my opinion debugging will be unrealistic when we want to simulate the entire bakery on distributed systems next week. I had trouble figuring out which agent was not calling the _finsihed()_ method at the right time when I had just 4 agents running. After a while, we figured out that only one agent among the four needs to make use of the timer. Therefore we could really simplify our debugging since we now had to worry about properly calling the _finsihed()_ in just one agent.

I do not yet get the reason why you feel that a two level base class is not a good idea. It essentially does the same things, except you now have a clear separation of SimpleAgents and TimedAgents and have to worry less about calling _finsihed()_.

**Comment by Sushant-Chavan** [comment]
Hi @argenos ,
Since we can have many agents that act as interfaces/auctioneers if each of these agents has to wait for one time step of an hour, we may end up never delivering the products on time since we spend a lot of time at each of these intermediate agents (we have 6 agent in the skeleton of the architecture which means we are already left with just 18 hours to finish everything else). 

This is the reason I propose that such agents should not depend on the clockAgent. However if others feel that this change is not needed, we can skip this refactoring task.

**Comment by argenos** [comment]
The solution might be to increase the resolution of the timeKeeper agent to minutes, and the time step might be 10 minutes at a time. 

This would also address the issue of the cooling and heating rate.

**Comment by Sushant-Chavan** [comment]
@argenos I agree with this. I still have one question pending about how to call _finished_ when an agent is supposed to receive messages quite late in the day (for example the MailboxAgent). I described this issue in detail earlier and am quoting here for easy reference:

> The very requirement that the behavior is blocked until a new message arrives can cause deadlock issues. For example, our TransportAgent that is in the delivery stage will never receive a message until there are some boxes that need to be delivered. Lets assume all the previous stages take 10 hrs to complete, so the first message that will be posted to the transport agent will be after 10 hrs. Now if the cyclic behavior to call finished() is blocked (as per your suggestion), we will never be able to call finish (as we ware waiting for a new message to wake up the behavior) and therefore the timer will never update time. We will be stuck in kind of a deadlock situation.

**Comment by argenos** [comment]
> The very requirement that the behavior is blocked until a new message arrives can cause deadlock issues. For example, our TransportAgent that is in the delivery stage will never receive a message until there are some boxes that need to be delivered. Lets assume all the previous stages take 10 hrs to complete, so the first message that will be posted to the transport agent will be after 10 hrs. Now if the cyclic behavior to call finished() is blocked (as per your suggestion), we will never be able to call finish (as we ware waiting for a new message to wake up the behavior) and therefore the timer will never update time. We will be stuck in kind of a deadlock situation.

This sounds like a bug to me, but @DharminB might know better. 

Would it be fair to ask @HBRS-MAAS/commitment_issues to do a pull request with the new resolution?
And if the blocking behavior indeed turns out to be a bug, can @HBRS-MAAS/right-brothers make a fix and create a pull request?

**Comment by DharminB** [comment]
> The very requirement that the behavior is blocked until a new message arrives can cause deadlock issues. For example, our TransportAgent that is in the delivery stage will never receive a message until there are some boxes that need to be delivered. Lets assume all the previous stages take 10 hrs to complete, so the first message that will be posted to the transport agent will be after 10 hrs. Now if the cyclic behavior to call finished() is blocked (as per your suggestion), we will never be able to call finish (as we ware waiting for a new message to wake up the behavior) and therefore the timer will never update time. We will be stuck in kind of a deadlock situation.
> This sounds like a bug to me, but @DharminB might know better. 

You are right, it sounds like a bug to me as well. But in reality, it is not. We actually tested this, and you can too. Just launch an agent which only has `CyclicBehaviour`s and comply with the suggestions given [here](https://github.com/HBRS-MAAS/project/issues/39#issuecomment-438866544). Now, only launch `TimeKeeper` and this agent from `Start.java`. The output will be that the time increases quite fast. The small detail that is easily forgotten is that all behaviour as unblocked when **any** message arrives. This means all the behaviours are unblocked when `timeStep` message arrives. This ensures that the agents which only have server kind of behaviours will also call `finished()` method. @HBRS-MAAS/commitment_issues

**Comment by DharminB** [comment]
> Like I said, the StreetNetwork is just an example (one among the potentially many), Even if we assume that we make StreetNetwork an Object, how do you say we handle other agents such as the TransportAgent which is an auctioneer or the MailboxAgent (acting as a relay) which just receives messages from a single truck and forwards copies of it to interested agents?. 

For autioneer, I would assume, it is similar to customer agent. The example [here](https://github.com/HBRS-MAAS/project/issues/39#issuecomment-438866544) could be of some help. For relay type agents, we propose the use of an agent which has `CyclicBehaviour` which relays message as soon as it gets. As we have mentioned [here](https://github.com/HBRS-MAAS/project/issues/39#issuecomment-438866544), these kind of behaviours do not need to (should not) be blocked based on `allowAction`. This is because server kind of behaviours are for providing service which we assume is instantaneous.  

> Also since the topic of discussion is how to improve the BaseAgent to satisfy different types of agents and not about the design of StreetNetwork in particular, I would like to talk on a general scale from here onwards.

The discussion is about existance of a bug. Bug reports need to be specific for the developer to recreate the error and solve it. Also, the entire point of having `BaseAgent` is to integrate agents for Bakery simulation so that they can keep in sync with other agents based on time and facilitate visualisation. The methods like `register` and `deRegister` are just there because we felt that it would help everyone save some time. They are not mentioned in requirements. If an agent wants to just use register without using timekeeper stuff, they can. (**Note**: when doing so the blocking based on `allowAction` should not be used and timekeeper should not be launched).

> I do not yet get the reason why you feel that a two level base class is not a good idea. It essentially does the same things, except you now have a clear separation of SimpleAgents and TimedAgents and have to worry less about calling _finsihed()_.

Because the `SimpleAgent` that is mentioned above is a normal regular old `Agent` (like the one in tutorial assignment). As we have previously mentioned, according to [this](https://user-images.githubusercontent.com/17234248/48140791-ce1a9880-e2a9-11e8-8605-e49b2bb1abc7.png) design, all agents execpt timekeeper and visualisation, all agents have to remain inside the bounds of time. We can however make timekeeper agent only wait for agents with certain `name`. This means, if an agent does not want to be inside simulation world but still wants to talk to agents inside the simulation then it has to call `this.register("some-agent-type", "NAME")` where name must not be `JADE-bakery`. This feature is not present now, but if @argenos and @HBRS-MAAS/commitment_issues agree, we can push that quite soon.

**Comment by argenos** [comment]
I believe that based on our discussion yesterday the agreement was to handle this through a smaller time step (10 min increments), not changing who registers with the time keeper agent or not.

**Comment by DharminB** [comment]
> I believe that based on our discussion yesterday the agreement was to handle this through a smaller time step (10 min increments), not changing who registers with the time keeper agent or not.

We believe, that would not really solve the issue. It will just keep it at bay for the time being. The supposed issue will occur again when the problem is scaled. That change, if everyone deems neccessary, can be made and incorporated in communication between timekeeper and baseAgent. Also, I believe, the original issue is about registering. I am quoting a small part of the original bug report message below.

> We have a few agents which do not depend on the time such as a StreetNetworkAgent which only responds to queries related to time to travel or path between two nodes. We would like to have a baseAgent that helps us register with Yellow pages, but does not involve dealing with the clock agent.

**Comment by DharminB** [comment]
> I don’t have anything in particular against splitting the base agent and a time or simulated agent, but I’m skeptical about their use other than visualization or few exceptions.
> If the changes are significant from the original proposal, the whole course needs to be notified.

@argenos We agree completely. We have yet to see such a use ourselves.
 
> Regardless of your decision about that, a smaller time step is needed and the pull request for that should also be ready by next week.

We will have pull request fixing following bugs
- Time step is 10 minutes instead of 1 hour (though it would be better to update scenario files first). For example
``` 
orderDate: {
    day: 3,
    hour: 12,
    timeStep: 2
}
```
**or**
```
orderDate: {
    day: 3,
    timeStep: 87
}
```
  In the latter example, timeStep is between 0 and 120 (24 hours * 6 slots per hour)
- time keeper will only check for agents who registered to yellow pages with name `JADE-bakery`

**Comment by argenos** [comment]
I think it’s safe to assume that the order date happens 003.12.00, i.e. minute 0 of the hour mentioned. That avoids the confusion between time steps and minutes, since the time step is mostly for the internal agents. 

Or put differently, the dates can be considered as ddd.hh.mm and minutes are increased in multiples of 10 instead of multiples of 1.

**Comment by DharminB** [comment]
Okay. Please let us know if you change your mind.
