### ISSUE TITLE
Recipe Action (Out of) Order?

### ISSUE THREAD

**Issue by emassey2** [HBRS-MAAS/project#44]
# @argenos 

It would appear that some items in the bakeries.json file are possibly out of order. For example in the Multigrain Bread recipe "cooling" comes before "proofing" and "baking". Does this imply that all actions before "baking" (which happens in the Baking Stage) should happen in the Dough Preparation Stage?

Currently, we are under the impression that the Dough Preparation Stage should be responsible for "Kneading", "Resting", 'Item Preparation", and "Proofing" and thus any action that happens before all of these actions are completed poses a problem.

[https://github.com/HBRS-MAAS/project/blob/master/src/main/resources/config/sample/bakeries.json](url)

**Comment by argenos** [comment]
No, they are not out of order.  Since we are right now going through the stages sequentially, assume for the time being that anything that happens before proofing, is part of the dough preparation stage. 

Similarly, anything that happens between proofing and before cooling is part of baking, and any left over actions are part of packaging. I’ll make sure the next scenario only includes one instance of the actions proofing and cooling per recipe. 

Later, depending on the time, the stages won’t be necessarily sequential. 

Cc @HBRS-MAAS
