### ISSUE TITLE
TimeKeeper agent does not terminate.

### ISSUE THREAD

**Issue by anenriquez** [HBRS-MAAS/project#52]
How should the TimeKeeper agent terminate? Should the termination be triggered by another agent? The function takeDown() of the TimeKeeper is currently empty.

**Comment by DharminB** [comment]
We were hoping to have a functionality such that the timekeeper agent will start all other agents before the simluation starts according to the `meta.json` file. It will shutdown the platform at the end of simulation. 

This, however, cannot be done unless we know how many agents of which kind are to be launched. It is obvious for customer or order processor, but it is not for others. We would have to wait till the complete design is fixed in place. 

If you are looking for a temporary solution, whenever you call any tests with multiple agents along with timeKeeper (but not all agents in project), have one of the agents implement shutdown behaviour provided in `dummyAgent.java` when you want to end the simulation. For example, in customer - orderProcessor scenario, when the customer receives confirmation from order processor, it adds shutdown behaviour. This solution is better in  ways
1. It is using the design we are used to from tutorial assignment and does not need radical changes
2. We would not like to wait till the end of simulation (`day 12 hour 23`) if the agents we are interested to test end their functionlity at `day 3 hour 12` and do nothing except call `finished()` for the rest of the simulation.

**Comment by DharminB** [comment]
> In any case, please check #55, that meta file should match the scenario files.

@argenos 
Things that match
- Number of bakeries
- Number of orders
- Number of customers (including their types)

Things that don't match
- duration in days
- delivery

Not checked
- products

**Comment by argenos** [comment]
The delivery might be because of the changes I made yesterday. Will rerun the meta script to check. 

What’s the difference in duration?

**Comment by DharminB** [comment]
> What’s the difference in duration?

In `clients.json`, there are orders which have order and delivery date with day 31. 
ref: [Line 844](https://github.com/HBRS-MAAS/project/blob/1dfe99f098b3565c23d442faac85b7b1d94963d6/src/main/resources/config/small/clients.json#L844)

**Comment by argenos** [comment]
Either that, or end the simulation once all orders are completed.

**Comment by argenos** [comment]
Can this be closed?

**Comment by DharminB** [comment]
Yes. Please close this.
