### ISSUE TITLE
Including interface agent tests on start

### ISSUE THREAD

**Issue by argenos** [HBRS-MAAS/project#62]
The `Start.java` doesn't currently include the interface agents. Ideally, we would include them and run some tests in Travis. @DharminB and @Dr4gonbl4de will create some pull requests with proposals for updating this file. 

cc @HBRS-MAAS

**Comment by Dr4gonbl4de** [comment]
See pull request #63 for my approach to change the start class

**Comment by DharminB** [comment]
Proposal for `Start.java` from @HBRS-MAAS/right-brothers is in #65

**Comment by argenos** [comment]
@HBRS-MAAS please take a look and comment on this thread for your preferred option!

**Comment by Dr4gonbl4de** [comment]
I would prefer my proposed solution, because it is easier to merge the solution of every group into the upstream. The main changes are made in an extra file that doesn't conflict with any other file of any group. Moreover every Group can easyly use class variables and method inside the corresponding initializer class which would possibly result in conflicts in the result proposed by thr right-brothers

**Comment by argenos** [comment]
@HBRS-MAAS deadline to decide this was yesterday, I'll extend this deadline by 22:00 today, and will merge one of the solutions by tomorrow morning.
