### ISSUE TITLE
CoolingRackAgent is not matching the conversation ID of ACL messages

### ISSUE THREAD

**Issue by anenriquez** [HBRS-MAAS/project#68]
In the documentation for the CoolingRackAgent, it says that conversation ID should be "cooled-product-" + counter.toString()", but the CoolingRackAgent does not seem to be matching the conversation ID when receiving the message. How is the conversation ID used by the CoolingRackAgent and is the counter in the ID required? @HBRS-MAAS/right-brothers 

Thanks

**Comment by DharminB** [comment]
This is a bug. Thank you for letting us know. A pull request is created "solving" this issue. 
Also, the cooling racks only uses the conversation id when sending the messages but does not check the convesation id of the messages it receives. The use of conversation id is mentioned in FICA rules. We think, it is supposed to be unique because then each message and each convesation can be tracked and what effect it had to the receiver. In our bakery scenario it only makes sense because the visualisation agents will most probably use this information.

**Comment by anenriquez** [comment]
Thanks for looking into this. We are using conversation ID to filter the messages received so that if several messages are sent, we only receive the one that matches the ID of the conversation. We ran into some issues where agents were receiving messages that did not match the ID.

**Comment by DharminB** [comment]
@anenriquez Could you please review #71 ? I would like to merge into develop ASAP.
