### ISSUE TITLE
Integrate customer with orderProcessing

### ISSUE THREAD

**Issue by DharminB** [HBRS-MAAS/project#91]
@HBRS-MAAS/jsw 
We need customer agent to work in order to test the integrated code for baking stage. 
It would be greatly appreciated if you could integrate customer agent with orderProcessing agent.

Also, please take a look at #90 and #94 and make necessary changes if needed. We are using that initializer.

**Comment by widyaaulia** [comment]
So, looking at the error, it is in the includeLocation function that it gives an error. That function is basically just putting a location inside the order because the location information in the config file is outside the "orders". And the location is a null. So, order.put("location", location)

The only reason I can think of by only looking at the info you have given me, that "put" is not working for null. We use json 2018 as we followed team-pjt of order processing. Previously, we used the older version and some of the function is not available yet. If that is not the answer, would you tell me what other code from us that you use beside start.java, data.java, and customerAgent.java?

**Comment by DharminB** [comment]
This was my mistake. I think as you pointed out, json 2018 might have been a problem. I may have an older gradle file running. Sorry for the confusion. I will change the title and goal of this issue to reflect second part (integration of customer and orderProcessing agent).
